### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Ehsan-c137** [sb16072007/hr-dark-vscode#1]
Hello 
i think the contrast of the colors are a bit too much, if you fix it that will be great.

**Comment by sb16072007** [comment]
@Ehsan-c137 Thanks for your feedback. New version of HR Dark (v0.1.0 -> v0.2.0) has been uploaded. You can download the new version at [https://marketplace.visualstudio.com/items?itemName=SoubikBhui16.hr-dark](https://marketplace.visualstudio.com/items?itemName=SoubikBhui16.hr-dark). If you have any other doubt you can create an issue here.
